services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db

    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite_app
    restart: unless-stopped
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  postgres_data:
