"""small fix

Revision ID: 31d5599a43e1
Revises: dd90039103fe
Create Date: 2026-05-16 19:12:16.099906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d5599a43e1'
down_revision: Union[str, Sequence[str], None] = 'dd90039103fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teams_event_id_fkey'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('teams_event_id_fkey'), 'teams', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
