"""Dodanie prawie wszystkich modeli

Revision ID: 5aa03714d76f
Revises: 1b083bb0b188
Create Date: 2026-05-15 21:57:59.278741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa03714d76f'
down_revision: Union[str, Sequence[str], None] = '1b083bb0b188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
