"""create_events_and_participations_tables

Revision ID: dd90039103fe
Revises: 6e0e76252fbb
Create Date: 2026-05-16 18:24:52.994162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd90039103fe'
down_revision: Union[str, Sequence[str], None] = '6e0e76252fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='participationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participations_id'), 'participations', ['id'], unique=False)
    op.alter_column('team_members', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'GHOST', name='teammemberstatus'),
               nullable=False)
    op.add_column('teams', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'teams', ['name'])
    op.drop_constraint(op.f('teams_captain_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('teams', 'captain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('captain_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_captain_id_fkey'), 'teams', 'users', ['captain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'owner_id')
    op.alter_column('team_members', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'GHOST', name='teammemberstatus'),
               nullable=True)
    op.drop_index(op.f('ix_participations_id'), table_name='participations')
    op.drop_table('participations')
    # ### end Alembic commands ###
