"""Add matches model and remove team score result

Revision ID: f5fbc99e0bb1
Revises: 014e3dfa7905
Create Date: 2026-05-24 23:12:53.210247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5fbc99e0bb1'
down_revision: Union[str, Sequence[str], None] = '014e3dfa7905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('participation_a_id', sa.Integer(), nullable=False),
    sa.Column('participation_b_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('team_a_score', sa.Integer(), nullable=True),
    sa.Column('team_b_score', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participation_a_id'], ['participations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participation_b_id'], ['participations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.drop_table('team_score_results')
    op.add_column('results', sa.Column('place', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'place')
    op.create_table('team_score_results',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['results.id'], name=op.f('team_score_results_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_score_results_pkey'))
    )
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
